// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WfoA5g4NVNutSQGcJInI9nHIBbOL0aw',
    appId: '1:368790947197:web:67a5321611484d76083814',
    messagingSenderId: '368790947197',
    projectId: 'clinicad-b150f',
    authDomain: 'clinicad-b150f.firebaseapp.com',
    storageBucket: 'clinicad-b150f.firebasestorage.app',
    measurementId: 'G-DHY8726X08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAzL5Pm3wksaoozGEJGN4wFfZgacKrVQ',
    appId: '1:368790947197:android:db12be51997424d0083814',
    messagingSenderId: '368790947197',
    projectId: 'clinicad-b150f',
    storageBucket: 'clinicad-b150f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2bOyZn3lFnL6HLGN2UUKIOCDllwao58',
    appId: '1:368790947197:ios:1e8b03f8e8bdce8d083814',
    messagingSenderId: '368790947197',
    projectId: 'clinicad-b150f',
    storageBucket: 'clinicad-b150f.firebasestorage.app',
    iosBundleId: 'com.example.sistemaDental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_WfoA5g4NVNutSQGcJInI9nHIBbOL0aw',
    appId: '1:368790947197:web:ab24d5a224aa5527083814',
    messagingSenderId: '368790947197',
    projectId: 'clinicad-b150f',
    authDomain: 'clinicad-b150f.firebaseapp.com',
    storageBucket: 'clinicad-b150f.firebasestorage.app',
    measurementId: 'G-6VBT8846G6',
  );
}
