// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0JHL6UtTPX3hVYHR5LK3r2aahHMFxXUU',
    appId: '1:61959782073:web:a6a116dba2b4cbbb7da568',
    messagingSenderId: '61959782073',
    projectId: 'dentalsync-484e0',
    authDomain: 'dentalsync-484e0.firebaseapp.com',
    storageBucket: 'dentalsync-484e0.firebasestorage.app',
    measurementId: 'G-0DC822SE9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk_e4tGeCfd6lyUAwr3EE9tIQBpCvl1Zw',
    appId: '1:61959782073:android:cba2baa69c2249937da568',
    messagingSenderId: '61959782073',
    projectId: 'dentalsync-484e0',
    storageBucket: 'dentalsync-484e0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5-xSA9yGRTqNL9RLZfTPt46OUAnmsKXI',
    appId: '1:61959782073:ios:07ec4c92ad1ae9e17da568',
    messagingSenderId: '61959782073',
    projectId: 'dentalsync-484e0',
    storageBucket: 'dentalsync-484e0.firebasestorage.app',
    iosBundleId: 'com.example.sistemaDental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0JHL6UtTPX3hVYHR5LK3r2aahHMFxXUU',
    appId: '1:61959782073:web:7103c544c87b48467da568',
    messagingSenderId: '61959782073',
    projectId: 'dentalsync-484e0',
    authDomain: 'dentalsync-484e0.firebaseapp.com',
    storageBucket: 'dentalsync-484e0.firebasestorage.app',
    measurementId: 'G-VCX8NTRSB1',
  );
}
